// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Source: "GIS 2026 PO Settings-3.xlsx", sheet "KPI Template", table range A1:M90.
// Every value below is the exact, verbatim workbook value (typos, stray quotes,
// the U+00D7 multiplication sign, trailing spaces and the blank row-32 frequency are
// preserved intentionally for audit fidelity). Canonicalisation happens elsewhere.

export type SourceTargetType = "Percentage" | "Number";

export interface WorkbookSourceRow {
  /** Actual 1-based spreadsheet row number (2..90, skipping blank separators). */
  sourceRowNumber: number;
  /** Column A 'S/N' — blank in every data row. */
  sourceSN: string | null;
  sourceEmployeeName: string;
  sourceEmployeeId: string;
  sourceRole: string;
  sourceDepartment: string;
  sourceUnit: string;
  sourceLocation: string;
  sourceObjective: string;
  sourceMetric: string;
  sourceWeight: number;
  /** Percentages stored as decimals (0.2, 1); numbers as-is (1, 4, 20). */
  sourceTarget: number;
  sourceTargetType: SourceTargetType;
  /** null where the workbook cell is blank (row 32). */
  sourceFrequency: string | null;
}

export const SOURCE_ROWS: readonly WorkbookSourceRow[] = [
  {
    sourceRowNumber: 2,
    sourceSN: null,
    sourceEmployeeName: "Mr Timothy Olutayo Olugbenro",
    sourceEmployeeId: "IKD030835",
    sourceRole: "Geographic Information Systems Lead",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Shomolu B/U",
    sourceObjective:
      "Ensure the accuracy and quality of all GIS data and map products delivered by the team.",
    sourceMetric:
      "Reduce the number of identified errors in GIS deliverables by 20% compared to the previous year.",
    sourceWeight: 10,
    sourceTarget: 0.2,
    sourceTargetType: "Percentage",
    sourceFrequency: "Monthly",
  },
  {
    sourceRowNumber: 3,
    sourceSN: null,
    sourceEmployeeName: "Mr Timothy Olutayo Olugbenro",
    sourceEmployeeId: "IKD030835",
    sourceRole: "Geographic Information Systems Lead",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Shomolu B/U",
    sourceObjective:
      "Full integration of GIS data to ensure 100% accuracy in capturing all IE network assets.ts ",
    sourceMetric:
      "Full integration of GIS data to ensure 100% accuracy in capturing all IE network assets",
    sourceWeight: 20,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Monthly",
  },
  {
    sourceRowNumber: 4,
    sourceSN: null,
    sourceEmployeeName: "Mr Timothy Olutayo Olugbenro",
    sourceEmployeeId: "IKD030835",
    sourceRole: "Geographic Information Systems Lead",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Shomolu B/U",
    sourceObjective:
      "Identifies and implement one oustanding  new technologies to improve network efficiency and reliability.",
    sourceMetric:
      "The contribution influences both quantitative and qualitative value, leading to cost savings and enhancing the overall impact on the business",
    sourceWeight: 20,
    sourceTarget: 1,
    sourceTargetType: "Number",
    sourceFrequency: "Annually",
  },
  {
    sourceRowNumber: 5,
    sourceSN: null,
    sourceEmployeeName: "Mr Timothy Olutayo Olugbenro",
    sourceEmployeeId: "IKD030835",
    sourceRole: "Geographic Information Systems Lead",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Shomolu B/U",
    sourceObjective:
      "Provide technical and mentorship training to GIS Specialists and Analysts.",
    sourceMetric:
      "Conduct at least one in every quarter technical training or knowledge-sharing session for the team.",
    sourceWeight: 15,
    sourceTarget: 4,
    sourceTargetType: "Number",
    sourceFrequency: "Quarterly",
  },
  {
    sourceRowNumber: 6,
    sourceSN: null,
    sourceEmployeeName: "Mr Timothy Olutayo Olugbenro",
    sourceEmployeeId: "IKD030835",
    sourceRole: "Geographic Information Systems Lead",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Shomolu B/U",
    sourceObjective:
      "Complete 100% of GIS projects within agreed timelines to support organizational objectives",
    sourceMetric: "Projects completed on time / Total projects × 100",
    sourceWeight: 15,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Monthly",
  },
  {
    sourceRowNumber: 8,
    sourceSN: null,
    sourceEmployeeName: "Mr Oladipupo Olanrewaju Eboda",
    sourceEmployeeId: "IKD041386",
    sourceRole: "Geographic Information Systems Lead",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Akowonjo BU",
    sourceObjective:
      "Ensure the accuracy and quality of all GIS data and map products delivered by the team.",
    sourceMetric:
      "Reduce the number of identified errors in GIS deliverables by 20% compared to the previous year.",
    sourceWeight: 10,
    sourceTarget: 0.2,
    sourceTargetType: "Percentage",
    sourceFrequency: "Monthly",
  },
  {
    sourceRowNumber: 9,
    sourceSN: null,
    sourceEmployeeName: "Mr Oladipupo Olanrewaju Eboda",
    sourceEmployeeId: "IKD041386",
    sourceRole: "Geographic Information Systems Lead",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Akowonjo BU",
    sourceObjective:
      "Full integration of GIS data to ensure 100% accuracy in capturing all IE network assets",
    sourceMetric:
      "Full integration of GIS data to ensure 100% accuracy in capturing all IE network assets",
    sourceWeight: 20,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Monthly",
  },
  {
    sourceRowNumber: 10,
    sourceSN: null,
    sourceEmployeeName: "Mr Oladipupo Olanrewaju Eboda",
    sourceEmployeeId: "IKD041386",
    sourceRole: "Geographic Information Systems Lead",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Akowonjo BU",
    sourceObjective:
      "Identifies and implement one oustanding  new technologies to improve network efficiency and reliability.",
    sourceMetric:
      "The contribution influences both quantitative and qualitative value, leading to cost savings and enhancing the overall impact on the business",
    sourceWeight: 20,
    sourceTarget: 1,
    sourceTargetType: "Number",
    sourceFrequency: "Annually",
  },
  {
    sourceRowNumber: 11,
    sourceSN: null,
    sourceEmployeeName: "Mr Oladipupo Olanrewaju Eboda",
    sourceEmployeeId: "IKD041386",
    sourceRole: "Geographic Information Systems Lead",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Akowonjo BU",
    sourceObjective:
      "Provide technical and mentorship training to GIS Specialists and Analysts.",
    sourceMetric:
      "Conduct at least one in every quarter technical training or knowledge-sharing session for the team.",
    sourceWeight: 15,
    sourceTarget: 4,
    sourceTargetType: "Number",
    sourceFrequency: "Quarterly",
  },
  {
    sourceRowNumber: 12,
    sourceSN: null,
    sourceEmployeeName: "Mr Oladipupo Olanrewaju Eboda",
    sourceEmployeeId: "IKD041386",
    sourceRole: "Geographic Information Systems Lead",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Akowonjo BU",
    sourceObjective:
      "Complete 100% of GIS projects within the agreed-upon time timelines to support organizational objectives",
    sourceMetric: "Projects completed on time / Total projects × 100",
    sourceWeight: 15,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Monthly",
  },
  {
    sourceRowNumber: 14,
    sourceSN: null,
    sourceEmployeeName: "Mr Lukmon Olawale Adedo",
    sourceEmployeeId: "IKD034693",
    sourceRole: "Geo Database Specialist",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Company Head Office",
    sourceObjective:
      "Ensure the integrity, security, and optimal performance of the enterprise geodatabase.",
    sourceMetric:
      "Perform and document weekly database health checks with zero instances of unscheduled downtime due to database issues.",
    sourceWeight: 20,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Weekly",
  },
  {
    sourceRowNumber: 15,
    sourceSN: null,
    sourceEmployeeName: "Mr Lukmon Olawale Adedo",
    sourceEmployeeId: "IKD034693",
    sourceRole: "Geo Database Specialist",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Company Head Office",
    sourceObjective: "Provide technical and mentorship training to GIS Analysts.",
    sourceMetric:
      "Conduct at least one in every quarter technical training or knowledge-sharing session for the team.",
    sourceWeight: 10,
    sourceTarget: 4,
    sourceTargetType: "Number",
    sourceFrequency: "Quarterly",
  },
  {
    sourceRowNumber: 16,
    sourceSN: null,
    sourceEmployeeName: "Mr Lukmon Olawale Adedo",
    sourceEmployeeId: "IKD034693",
    sourceRole: "Geo Database Specialist",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Company Head Office",
    sourceObjective:
      "Ensure the accuracy and quality of all GIS data during maitenance window with the commercial department.",
    sourceMetric:
      "Reduce the number of identified errors in GIS deliverables by 20% compared to the previous year.",
    sourceWeight: 10,
    sourceTarget: 20,
    sourceTargetType: "Number",
    sourceFrequency: "Monthly",
  },
  {
    sourceRowNumber: 17,
    sourceSN: null,
    sourceEmployeeName: "Mr Lukmon Olawale Adedo",
    sourceEmployeeId: "IKD034693",
    sourceRole: "Geo Database Specialist",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Company Head Office",
    sourceObjective:
      "Full integration of GIS data to ensure 100% accuracy in capturing all IE network assets.",
    sourceMetric: "GDB Folders",
    sourceWeight: 20,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Monthly",
  },
  {
    sourceRowNumber: 18,
    sourceSN: null,
    sourceEmployeeName: "Mr Lukmon Olawale Adedo",
    sourceEmployeeId: "IKD034693",
    sourceRole: "Geo Database Specialist",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Company Head Office",
    sourceObjective:
      "Identifies and implement one oustanding  new technologies to improve network efficiency and reliability.",
    sourceMetric: "GIS Project Dashboard",
    sourceWeight: 20,
    sourceTarget: 1,
    sourceTargetType: "Number",
    sourceFrequency: "Annually",
  },
  {
    sourceRowNumber: 20,
    sourceSN: null,
    sourceEmployeeName: "Mr Chiedu Conweh",
    sourceEmployeeId: "IKD042840",
    sourceRole: "Geographic Information Systems Specialist",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Ikorodu B/U",
    sourceObjective:
      "Complete 100% of GIS projects within agreed timelines to support organizational objectives",
    sourceMetric: "Projects completed on time / Total projects × 100",
    sourceWeight: 15,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Monthly",
  },
  {
    sourceRowNumber: 21,
    sourceSN: null,
    sourceEmployeeName: "Mr Chiedu Conweh",
    sourceEmployeeId: "IKD042840",
    sourceRole: "Geographic Information Systems Specialist",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Ikorodu B/U",
    sourceObjective: "Resolve 100% of GIS technical issues within 24",
    sourceMetric:
      "Number of GIS Technical Issues resolved within 24hrs / Total issues × 100 ",
    sourceWeight: 10,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Daily",
  },
  {
    sourceRowNumber: 22,
    sourceSN: null,
    sourceEmployeeName: "Mr Chiedu Conweh",
    sourceEmployeeId: "IKD042840",
    sourceRole: "Geographic Information Systems Specialist",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Ikorodu B/U",
    sourceObjective: "Provide technical and mentorship training to GIS Analysts.",
    sourceMetric:
      "Conduct at least one in every quarter technical training or knowledge-sharing session for the team.",
    sourceWeight: 15,
    sourceTarget: 4,
    sourceTargetType: "Number",
    sourceFrequency: "Quarterly",
  },
  {
    sourceRowNumber: 23,
    sourceSN: null,
    sourceEmployeeName: "Mr Chiedu Conweh",
    sourceEmployeeId: "IKD042840",
    sourceRole: "Geographic Information Systems Specialist",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Ikorodu B/U",
    sourceObjective:
      "Full integration of GIS data to ensure 100% accuracy in capturing all IE network assets.",
    sourceMetric: "Percentage Archieved / Planned",
    sourceWeight: 20,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Monthly",
  },
  {
    sourceRowNumber: 24,
    sourceSN: null,
    sourceEmployeeName: "Mr Chiedu Conweh",
    sourceEmployeeId: "IKD042840",
    sourceRole: "Geographic Information Systems Specialist",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Ikorodu B/U",
    sourceObjective:
      "Identifies and implement one oustanding  new technologies to improve network efficiency and reliability.",
    sourceMetric:
      "The contribution influences both quantitative and qualitative value, leading to cost savings and enhancing the overall impact on the business",
    sourceWeight: 20,
    sourceTarget: 1,
    sourceTargetType: "Number",
    sourceFrequency: "Annually",
  },
  {
    sourceRowNumber: 26,
    sourceSN: null,
    sourceEmployeeName: "Mr Sheriff Baba Mohammed",
    sourceEmployeeId: "IKD034860",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Ikorodu B/U",
    sourceObjective:
      "Capture, process, and integrate spatial and non-spatial data from various sources into the GIS database.",
    sourceMetric:
      "Integrate 100% of new data within 2 business days of receipt and validation.",
    sourceWeight: 20,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Weekly",
  },
  {
    sourceRowNumber: 27,
    sourceSN: null,
    sourceEmployeeName: "Mr Sheriff Baba Mohammed",
    sourceEmployeeId: "IKD034860",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Ikorodu B/U",
    sourceObjective:
      "Perform quality assurance checks on all incoming and existing GIS data to ensure accuracy and completeness",
    sourceMetric:
      "Identify and correct an average of 20 data errors or inconsistencies per month.",
    sourceWeight: 15,
    sourceTarget: 20,
    sourceTargetType: "Number",
    sourceFrequency: "Monthly",
  },
  {
    sourceRowNumber: 28,
    sourceSN: null,
    sourceEmployeeName: "Mr Sheriff Baba Mohammed",
    sourceEmployeeId: "IKD034860",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Ikorodu B/U",
    sourceObjective:
      "Full integration of GIS data to ensure 100% accuracy in capturing all IE network assets.",
    sourceMetric: "Percentage Achieved / Planned",
    sourceWeight: 10,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Monthly",
  },
  {
    sourceRowNumber: 29,
    sourceSN: null,
    sourceEmployeeName: "Mr Sheriff Baba Mohammed",
    sourceEmployeeId: "IKD034860",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Ikorodu B/U",
    sourceObjective: "Resolve 100% of GIS technical issues within 24",
    sourceMetric:
      "Number of GIS Technical Issues resolved within 24hrs / Total issues × 100 ",
    sourceWeight: 15,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Daily",
  },
  {
    sourceRowNumber: 30,
    sourceSN: null,
    sourceEmployeeName: "Mr Sheriff Baba Mohammed",
    sourceEmployeeId: "IKD034860",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Ikorodu B/U",
    sourceObjective:
      "Identifies and implement one oustanding  new technologies to improve network efficiency and reliability.",
    sourceMetric:
      "The contribution influences both quantitative and qualitative value, leading to cost savings and enhancing the overall",
    sourceWeight: 20,
    sourceTarget: 1,
    sourceTargetType: "Number",
    sourceFrequency: "Annually",
  },
  {
    sourceRowNumber: 32,
    sourceSN: null,
    sourceEmployeeName: "Mr Michael Ifeanyi Akudoro",
    sourceEmployeeId: "IKD034794",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Akowonjo B/U",
    sourceObjective:
      "Perform quality assurance checks on all incoming and existing GIS data to ensure accuracy and completeness..",
    sourceMetric:
      "Identify and correct an average of 20 data errors or inconsistencies per month.",
    sourceWeight: 15,
    sourceTarget: 20,
    sourceTargetType: "Number",
    sourceFrequency: null,
  },
  {
    sourceRowNumber: 33,
    sourceSN: null,
    sourceEmployeeName: "Mr Michael Ifeanyi Akudoro",
    sourceEmployeeId: "IKD034794",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Akowonjo B/U",
    sourceObjective:
      "Capture, process, and integrate spatial and non-spatial data from various sources into the GIS database.",
    sourceMetric:
      "Integrate 100% of new data within 2 business days of receipt and validation.",
    sourceWeight: 20,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Weekly",
  },
  {
    sourceRowNumber: 34,
    sourceSN: null,
    sourceEmployeeName: "Mr Michael Ifeanyi Akudoro",
    sourceEmployeeId: "IKD034794",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Akowonjo B/U",
    sourceObjective:
      "Full integration of GIS data to ensure 100% accuracy in capturing all IE network assets.",
    sourceMetric: "Percentage Archieved / Planned",
    sourceWeight: 10,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Monthly",
  },
  {
    sourceRowNumber: 35,
    sourceSN: null,
    sourceEmployeeName: "Mr Michael Ifeanyi Akudoro",
    sourceEmployeeId: "IKD034794",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Akowonjo B/U",
    sourceObjective: "Resolve 100% of GIS technical issues within 24",
    sourceMetric:
      '"Number of GIS Technical Issues resolved within 24hrs / Total issues × 100 "',
    sourceWeight: 15,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Daily",
  },
  {
    sourceRowNumber: 36,
    sourceSN: null,
    sourceEmployeeName: "Mr Michael Ifeanyi Akudoro",
    sourceEmployeeId: "IKD034794",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Akowonjo B/U",
    sourceObjective:
      "Identifies and implement one oustanding  new technologies to improve network efficiency and reliability.",
    sourceMetric:
      "The contribution influences both quantitative and qualitative value, leading to cost savings and enhancing the overall impact on the business",
    sourceWeight: 20,
    sourceTarget: 1,
    sourceTargetType: "Number",
    sourceFrequency: "Annually",
  },
  {
    sourceRowNumber: 38,
    sourceSN: null,
    sourceEmployeeName: "Mrs Grace Amarachi Chukwu",
    sourceEmployeeId: "IKD034604",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Oshodi B/U",
    sourceObjective:
      "Identifies and implement one oustanding  new technologies to improve network efficiency and reliability..",
    sourceMetric:
      "The contribution influences both quantitative and qualitative value, leading to cost savings and enhancing the overall impact on the business.",
    sourceWeight: 20,
    sourceTarget: 1,
    sourceTargetType: "Number",
    sourceFrequency: "Annually",
  },
  {
    sourceRowNumber: 39,
    sourceSN: null,
    sourceEmployeeName: "Mrs Grace Amarachi Chukwu",
    sourceEmployeeId: "IKD034604",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Oshodi B/U",
    sourceObjective:
      "Perform quality assurance checks on all incoming and existing GIS data to ensure accuracy and completeness..",
    sourceMetric:
      "Identify and correct an average of 20 data errors or inconsistencies per month.",
    sourceWeight: 15,
    sourceTarget: 20,
    sourceTargetType: "Number",
    sourceFrequency: "Monthly",
  },
  {
    sourceRowNumber: 40,
    sourceSN: null,
    sourceEmployeeName: "Mrs Grace Amarachi Chukwu",
    sourceEmployeeId: "IKD034604",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Oshodi B/U",
    sourceObjective:
      "Full integration of GIS data to ensure 100% accuracy in capturing all IE network assets.",
    sourceMetric: "Percentage Achieved / Planned",
    sourceWeight: 10,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Monthly",
  },
  {
    sourceRowNumber: 41,
    sourceSN: null,
    sourceEmployeeName: "Mrs Grace Amarachi Chukwu",
    sourceEmployeeId: "IKD034604",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Oshodi B/U",
    sourceObjective:
      "Capture, process, and integrate spatial and non-spatial data from various sources into the GIS database..",
    sourceMetric:
      "Integrate 100% of new data within 2 business days of receipt and validation.",
    sourceWeight: 20,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Weekly",
  },
  {
    sourceRowNumber: 42,
    sourceSN: null,
    sourceEmployeeName: "Mrs Grace Amarachi Chukwu",
    sourceEmployeeId: "IKD034604",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Oshodi B/U",
    sourceObjective: "Resolve 100% of GIS technical issues within 24.",
    sourceMetric:
      '"Number of GIS Technical Issues resolved within 24hrs / Total issues × 100 ".',
    sourceWeight: 15,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Daily",
  },
  {
    sourceRowNumber: 44,
    sourceSN: null,
    sourceEmployeeName: "Mrs Obianuju Esther Onwuasoanya",
    sourceEmployeeId: "IKD034769",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Oshodi B/U",
    sourceObjective:
      "Identifies and implement one oustanding  new technologies to improve network efficiency and reliability.",
    sourceMetric:
      "The contribution influences both quantitative and qualitative value, leading to cost savings and enhancing the overall impact on the business",
    sourceWeight: 20,
    sourceTarget: 1,
    sourceTargetType: "Number",
    sourceFrequency: "Annually",
  },
  {
    sourceRowNumber: 45,
    sourceSN: null,
    sourceEmployeeName: "Mrs Obianuju Esther Onwuasoanya",
    sourceEmployeeId: "IKD034769",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Oshodi B/U",
    sourceObjective:
      "Full integration of GIS data to ensure 100% accuracy in capturing all IE network assets.",
    sourceMetric: "Percentage Achieved / Planned",
    sourceWeight: 10,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Monthly",
  },
  {
    sourceRowNumber: 46,
    sourceSN: null,
    sourceEmployeeName: "Mrs Obianuju Esther Onwuasoanya",
    sourceEmployeeId: "IKD034769",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Oshodi B/U",
    sourceObjective: "Resolve 100% of GIS technical issues within 24 hrs.",
    sourceMetric:
      "Number of GIS Technical Issues resolved within 24hrs / Total issues × 100 ",
    sourceWeight: 15,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Daily",
  },
  {
    sourceRowNumber: 47,
    sourceSN: null,
    sourceEmployeeName: "Mrs Obianuju Esther Onwuasoanya",
    sourceEmployeeId: "IKD034769",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Oshodi B/U",
    sourceObjective:
      "Perform quality assurance checks on all incoming and existing GIS data to ensure accuracy and completeness.",
    sourceMetric:
      "Identify and correct an average of 20 data errors or inconsistencies per month.",
    sourceWeight: 15,
    sourceTarget: 20,
    sourceTargetType: "Number",
    sourceFrequency: "Monthly",
  },
  {
    sourceRowNumber: 48,
    sourceSN: null,
    sourceEmployeeName: "Mrs Obianuju Esther Onwuasoanya",
    sourceEmployeeId: "IKD034769",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Oshodi B/U",
    sourceObjective:
      "Capture, process, and integrate spatial and non-spatial data from various sources into the GIS database.",
    sourceMetric:
      "Integrate 100% of new data within 2 business days of receipt and validation.",
    sourceWeight: 20,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Weekly",
  },
  {
    sourceRowNumber: 50,
    sourceSN: null,
    sourceEmployeeName: "Mr Timothy Anuoluwapo Babatunde",
    sourceEmployeeId: "IKD034543",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Abule Egba B/U",
    sourceObjective:
      "Capture, process, and integrate spatial and non-spatial data from various sources into the GIS database.",
    sourceMetric:
      "Integrate 100% of new data within 2 business days of receipt and validation.",
    sourceWeight: 20,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Weekly",
  },
  {
    sourceRowNumber: 51,
    sourceSN: null,
    sourceEmployeeName: "Mr Timothy Anuoluwapo Babatunde",
    sourceEmployeeId: "IKD034543",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Abule Egba B/U",
    sourceObjective:
      "Perform quality assurance checks on all incoming and existing GIS data to ensure accuracy and completeness.",
    sourceMetric:
      "Identify and correct an average of 20 data errors or inconsistencies per month.",
    sourceWeight: 15,
    sourceTarget: 20,
    sourceTargetType: "Number",
    sourceFrequency: "Monthly",
  },
  {
    sourceRowNumber: 52,
    sourceSN: null,
    sourceEmployeeName: "Mr Timothy Anuoluwapo Babatunde",
    sourceEmployeeId: "IKD034543",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Abule Egba B/U",
    sourceObjective:
      "Full integration of GIS data to ensure 100% accuracy in capturing all IE network assets.",
    sourceMetric: "Percentage Archieved / Planned",
    sourceWeight: 10,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Monthly",
  },
  {
    sourceRowNumber: 53,
    sourceSN: null,
    sourceEmployeeName: "Mr Timothy Anuoluwapo Babatunde",
    sourceEmployeeId: "IKD034543",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Abule Egba B/U",
    sourceObjective: "Resolve 100% of GIS technical issues within 24 hours",
    sourceMetric:
      "Number of GIS Technical Issues resolved within 24hrs / Total issues × 100",
    sourceWeight: 15,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Daily",
  },
  {
    sourceRowNumber: 54,
    sourceSN: null,
    sourceEmployeeName: "Mr Timothy Anuoluwapo Babatunde",
    sourceEmployeeId: "IKD034543",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Abule Egba B/U",
    sourceObjective:
      "Identifies and implement one oustanding  new technologies to improve network efficiency and reliability.",
    sourceMetric:
      "Integrate 100% of new data within 2 business days of receipt and validation.",
    sourceWeight: 20,
    sourceTarget: 1,
    sourceTargetType: "Number",
    sourceFrequency: "Annually",
  },
  {
    sourceRowNumber: 56,
    sourceSN: null,
    sourceEmployeeName: "Mr Oluwasanmi Ayodele Ajala",
    sourceEmployeeId: "IKD034675",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Abule Egba B/U",
    sourceObjective:
      "Perform quality assurance checks on all incoming and existing GIS data to ensure accuracy and completeness",
    sourceMetric:
      "Identify and correct an average of 20 data errors or inconsistencies per month",
    sourceWeight: 15,
    sourceTarget: 20,
    sourceTargetType: "Number",
    sourceFrequency: "Monthly",
  },
  {
    sourceRowNumber: 57,
    sourceSN: null,
    sourceEmployeeName: "Mr Oluwasanmi Ayodele Ajala",
    sourceEmployeeId: "IKD034675",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Abule Egba B/U",
    sourceObjective:
      "Capture, process, and integrate spatial and non-spatial data from various sources into the GIS database",
    sourceMetric:
      "Integrate 100% of new data within 2 business days of receipt and validation",
    sourceWeight: 20,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Weekly",
  },
  {
    sourceRowNumber: 58,
    sourceSN: null,
    sourceEmployeeName: "Mr Oluwasanmi Ayodele Ajala",
    sourceEmployeeId: "IKD034675",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Abule Egba B/U",
    sourceObjective:
      "Full integration of GIS data to ensure 100% accuracy in capturing all IE network assets.",
    sourceMetric: "Percentage Archieved / Planned",
    sourceWeight: 10,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Monthly",
  },
  {
    sourceRowNumber: 59,
    sourceSN: null,
    sourceEmployeeName: "Mr Oluwasanmi Ayodele Ajala",
    sourceEmployeeId: "IKD034675",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Abule Egba B/U",
    sourceObjective: "Resolve 100% of GIS technical issues within 24",
    sourceMetric:
      "Number of GIS Technical Issues resolved within 24hrs / Total issues × 100 ",
    sourceWeight: 15,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Daily",
  },
  {
    sourceRowNumber: 60,
    sourceSN: null,
    sourceEmployeeName: "Mr Oluwasanmi Ayodele Ajala",
    sourceEmployeeId: "IKD034675",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Abule Egba B/U",
    sourceObjective:
      "Identifies and implement one oustanding  new technologies to improve network efficiency and reliability.",
    sourceMetric:
      "The contribution influences both quantitative and qualitative value, leading to cost savings and enhancing the overall impact on the business",
    sourceWeight: 20,
    sourceTarget: 1,
    sourceTargetType: "Number",
    sourceFrequency: "Annually",
  },
  {
    sourceRowNumber: 62,
    sourceSN: null,
    sourceEmployeeName: "Mrs Ruth Oluwaseun Dele-Aisida",
    sourceEmployeeId: "IKD043643",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Ikeja B/U",
    sourceObjective:
      "Capture, process, and integrate spatial and non-spatial data from various sources into the GIS database.",
    sourceMetric:
      "Integrate 100% of new data within 2 business days of receipt and validation.",
    sourceWeight: 20,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Weekly",
  },
  {
    sourceRowNumber: 63,
    sourceSN: null,
    sourceEmployeeName: "Mrs Ruth Oluwaseun Dele-Aisida",
    sourceEmployeeId: "IKD043643",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Ikeja B/U",
    sourceObjective:
      "Perform quality assurance checks on all incoming and existing GIS data to ensure accuracy and completeness.",
    sourceMetric:
      "Identify and correct an average of 20 data errors or inconsistencies per month.",
    sourceWeight: 15,
    sourceTarget: 20,
    sourceTargetType: "Number",
    sourceFrequency: "Monthly",
  },
  {
    sourceRowNumber: 64,
    sourceSN: null,
    sourceEmployeeName: "Mrs Ruth Oluwaseun Dele-Aisida",
    sourceEmployeeId: "IKD043643",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Ikeja B/U",
    sourceObjective:
      "Full integration of GIS data to ensure 100% accuracy in capturing all IE network assets.",
    sourceMetric: "Percentage Achieved / Planned",
    sourceWeight: 10,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Monthly",
  },
  {
    sourceRowNumber: 65,
    sourceSN: null,
    sourceEmployeeName: "Mrs Ruth Oluwaseun Dele-Aisida",
    sourceEmployeeId: "IKD043643",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Ikeja B/U",
    sourceObjective: "Resolve 100% of GIS technical issues within 24",
    sourceMetric:
      "Number of GIS Technical Issues resolved within 24hrs / Total issues × 100 ",
    sourceWeight: 15,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Daily",
  },
  {
    sourceRowNumber: 66,
    sourceSN: null,
    sourceEmployeeName: "Mrs Ruth Oluwaseun Dele-Aisida",
    sourceEmployeeId: "IKD043643",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Ikeja B/U",
    sourceObjective:
      "Identifies and implement one oustanding  new technologies to improve network efficiency and reliability.",
    sourceMetric:
      "The contribution influences both quantitative and qualitative value, leading to cost savings and enhancing the overall impact on the business",
    sourceWeight: 20,
    sourceTarget: 1,
    sourceTargetType: "Number",
    sourceFrequency: "Annually",
  },
  {
    sourceRowNumber: 68,
    sourceSN: null,
    sourceEmployeeName: "Mr Babatunde Temitope Akintayo",
    sourceEmployeeId: "IKD092080",
    sourceRole: "Geographic Information Systems Specialist",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Ikeja B/U",
    sourceObjective: "Resolve 100% of GIS technical issues within 24",
    sourceMetric:
      '"Number of GIS Technical Issues resolved within 24hrs / Total issues × 100 "',
    sourceWeight: 10,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Daily",
  },
  {
    sourceRowNumber: 69,
    sourceSN: null,
    sourceEmployeeName: "Mr Babatunde Temitope Akintayo",
    sourceEmployeeId: "IKD092080",
    sourceRole: "Geographic Information Systems Specialist",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Ikeja B/U",
    sourceObjective:
      "Identifies and implement one oustanding  new technologies to improve network efficiency and reliability.",
    sourceMetric:
      "The contribution influences both quantitative and qualitative value, leading to cost savings and enhancing the overall impact on the business",
    sourceWeight: 20,
    sourceTarget: 1,
    sourceTargetType: "Number",
    sourceFrequency: "Annually",
  },
  {
    sourceRowNumber: 70,
    sourceSN: null,
    sourceEmployeeName: "Mr Babatunde Temitope Akintayo",
    sourceEmployeeId: "IKD092080",
    sourceRole: "Geographic Information Systems Specialist",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Ikeja B/U",
    sourceObjective:
      'Complete 100% of GIS projects within agreed timelines to support organizational objectives"',
    sourceMetric: '"Projects completed on time / Total projects × 100"',
    sourceWeight: 15,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Monthly",
  },
  {
    sourceRowNumber: 71,
    sourceSN: null,
    sourceEmployeeName: "Mr Babatunde Temitope Akintayo",
    sourceEmployeeId: "IKD092080",
    sourceRole: "Geographic Information Systems Specialist",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Ikeja B/U",
    sourceObjective: "Provide technical and mentorship training to GIS Analysts.",
    sourceMetric:
      "Conduct at least one in every quarter technical training or knowledge-sharing session for the team.",
    sourceWeight: 15,
    sourceTarget: 4,
    sourceTargetType: "Number",
    sourceFrequency: "Quarterly",
  },
  {
    sourceRowNumber: 72,
    sourceSN: null,
    sourceEmployeeName: "Mr Babatunde Temitope Akintayo",
    sourceEmployeeId: "IKD092080",
    sourceRole: "Geographic Information Systems Specialist",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Ikeja B/U",
    sourceObjective:
      "Full integration of GIS data to ensure 100% accuracy in capturing all IE network assets.",
    sourceMetric: "Percentage Archieved / Planned",
    sourceWeight: 20,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Monthly",
  },
  {
    sourceRowNumber: 74,
    sourceSN: null,
    sourceEmployeeName: "Mr Abiola Julius Oduwaiye",
    sourceEmployeeId: "IKD112347",
    sourceRole: "Geographic Information Systems Specialist",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Company Head Office",
    sourceObjective: "Resolve 100% of GIS technical issues within 24",
    sourceMetric:
      '"Number of GIS Technical Issues resolved within 24hrs / Total issues × 100 "',
    sourceWeight: 10,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Daily",
  },
  {
    sourceRowNumber: 75,
    sourceSN: null,
    sourceEmployeeName: "Mr Abiola Julius Oduwaiye",
    sourceEmployeeId: "IKD112347",
    sourceRole: "Geographic Information Systems Specialist",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Company Head Office",
    sourceObjective:
      "Identifies and implement one oustanding  new technologies to improve network efficiency and reliability.",
    sourceMetric:
      "The contribution influences both quantitative and qualitative value, leading to cost savings and enhancing the overall impact on the business",
    sourceWeight: 20,
    sourceTarget: 1,
    sourceTargetType: "Number",
    sourceFrequency: "Annually",
  },
  {
    sourceRowNumber: 76,
    sourceSN: null,
    sourceEmployeeName: "Mr Abiola Julius Oduwaiye",
    sourceEmployeeId: "IKD112347",
    sourceRole: "Geographic Information Systems Specialist",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Company Head Office",
    sourceObjective:
      'Complete 100% of GIS projects within agreed timelines to support organizational objectives"',
    sourceMetric: '"Projects completed on time / Total projects × 100"',
    sourceWeight: 15,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Monthly",
  },
  {
    sourceRowNumber: 77,
    sourceSN: null,
    sourceEmployeeName: "Mr Abiola Julius Oduwaiye",
    sourceEmployeeId: "IKD112347",
    sourceRole: "Geographic Information Systems Specialist",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Company Head Office",
    sourceObjective: "Provide technical and mentorship training to GIS Analysts.",
    sourceMetric:
      "Conduct at least one in every quarter technical training or knowledge-sharing session for the team.",
    sourceWeight: 15,
    sourceTarget: 4,
    sourceTargetType: "Number",
    sourceFrequency: "Quarterly",
  },
  {
    sourceRowNumber: 78,
    sourceSN: null,
    sourceEmployeeName: "Mr Abiola Julius Oduwaiye",
    sourceEmployeeId: "IKD112347",
    sourceRole: "Geographic Information Systems Specialist",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Company Head Office",
    sourceObjective:
      "Full integration of GIS data to ensure 100% accuracy in capturing all IE network assets.",
    sourceMetric: "Percentage Archieved / Planned",
    sourceWeight: 20,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Monthly",
  },
  {
    sourceRowNumber: 80,
    sourceSN: null,
    sourceEmployeeName: "Ms Halima Olamide Hassan",
    sourceEmployeeId: "IKD112310",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Shomolu B/U",
    sourceObjective:
      "Capture, process, and integrate spatial and non-spatial data from various sources into the GIS database.",
    sourceMetric:
      "Integrate 100% of new data within 2 business days of receipt and validation.",
    sourceWeight: 20,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Weekly",
  },
  {
    sourceRowNumber: 81,
    sourceSN: null,
    sourceEmployeeName: "Ms Halima Olamide Hassan",
    sourceEmployeeId: "IKD112310",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Shomolu B/U",
    sourceObjective:
      "Perform quality assurance checks on all incoming and existing GIS data to ensure accuracy and completeness.",
    sourceMetric:
      "Identify and correct an average of 20 data errors or inconsistencies per month.",
    sourceWeight: 15,
    sourceTarget: 20,
    sourceTargetType: "Number",
    sourceFrequency: "Monthly",
  },
  {
    sourceRowNumber: 82,
    sourceSN: null,
    sourceEmployeeName: "Ms Halima Olamide Hassan",
    sourceEmployeeId: "IKD112310",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Shomolu B/U",
    sourceObjective:
      "Full integration of GIS data to ensure 100% accuracy in capturing all IE network assets.",
    sourceMetric: "Percentage Achieved / Planned",
    sourceWeight: 10,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Monthly",
  },
  {
    sourceRowNumber: 83,
    sourceSN: null,
    sourceEmployeeName: "Ms Halima Olamide Hassan",
    sourceEmployeeId: "IKD112310",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Shomolu B/U",
    sourceObjective: "Resolve 100% of GIS technical issues within 24",
    sourceMetric:
      "Number of GIS Technical Issues resolved within 24hrs / Total issues × 100 ",
    sourceWeight: 15,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Daily",
  },
  {
    sourceRowNumber: 84,
    sourceSN: null,
    sourceEmployeeName: "Ms Halima Olamide Hassan",
    sourceEmployeeId: "IKD112310",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Shomolu B/U",
    sourceObjective:
      "Identifies and implement one oustanding  new technologies to improve network efficiency and reliability.",
    sourceMetric:
      "The contribution influences both quantitative and qualitative value, leading to cost savings and enhancing the overall impact on the business",
    sourceWeight: 20,
    sourceTarget: 1,
    sourceTargetType: "Number",
    sourceFrequency: "Annually",
  },
  {
    sourceRowNumber: 86,
    sourceSN: null,
    sourceEmployeeName: "Mr. Jeleel Oloyede Ajetunmobi",
    sourceEmployeeId: "IKD112329",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Company Head Office",
    sourceObjective:
      "Capture, process, and integrate spatial and non-spatial data from various sources into the GIS database.",
    sourceMetric:
      "Integrate 100% of new data within 2 business days of receipt and validation.",
    sourceWeight: 20,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Weekly",
  },
  {
    sourceRowNumber: 87,
    sourceSN: null,
    sourceEmployeeName: "Mr. Jeleel Oloyede Ajetunmobi",
    sourceEmployeeId: "IKD112329",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Company Head Office",
    sourceObjective:
      "Perform quality assurance checks on all incoming and existing GIS data to ensure accuracy and completeness.",
    sourceMetric:
      "Identify and correct an average of 20 data errors or inconsistencies per month.",
    sourceWeight: 15,
    sourceTarget: 20,
    sourceTargetType: "Number",
    sourceFrequency: "Monthly",
  },
  {
    sourceRowNumber: 88,
    sourceSN: null,
    sourceEmployeeName: "Mr. Jeleel Oloyede Ajetunmobi",
    sourceEmployeeId: "IKD112329",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Company Head Office",
    sourceObjective:
      "Full integration of GIS data to ensure 100% accuracy in capturing all IE network assets.",
    sourceMetric: "Percentage Achieved / Planned",
    sourceWeight: 10,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Monthly",
  },
  {
    sourceRowNumber: 89,
    sourceSN: null,
    sourceEmployeeName: "Mr. Jeleel Oloyede Ajetunmobi",
    sourceEmployeeId: "IKD112329",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Company Head Office",
    sourceObjective: "Resolve 100% of GIS technical issues within 24",
    sourceMetric:
      "Number of GIS Technical Issues resolved within 24hrs / Total issues × 100 ",
    sourceWeight: 15,
    sourceTarget: 1,
    sourceTargetType: "Percentage",
    sourceFrequency: "Daily",
  },
  {
    sourceRowNumber: 90,
    sourceSN: null,
    sourceEmployeeName: "Mr. Jeleel Oloyede Ajetunmobi",
    sourceEmployeeId: "IKD112329",
    sourceRole: "Geographic Information Systems Analyst",
    sourceDepartment: "Technical Services",
    sourceUnit: "Technical Optimization",
    sourceLocation: "Company Head Office",
    sourceObjective:
      "Identifies and implement one oustanding  new technologies to improve network efficiency and reliability.",
    sourceMetric:
      "The contribution influences both quantitative and qualitative value, leading to cost savings and enhancing the overall impact on the business",
    sourceWeight: 20,
    sourceTarget: 1,
    sourceTargetType: "Number",
    sourceFrequency: "Annually",
  },
] as const;

export const WORKBOOK_META = {
  fileName: "GIS 2026 PO Settings-3.xlsx",
  sheetName: "KPI Template",
  tableRange: "A1:M90",
  dataRowCount: 75,
  employeeCount: 15,
  blankSeparatorRows: 14,
  frequencyDistribution: {
    Monthly: 31,
    Annually: 15,
    Quarterly: 6,
    Weekly: 10,
    Daily: 12,
    "(blank)": 1,
  },
  targetTypeDistribution: { Percentage: 44, Number: 31 },
} as const;
